# Generated by Django 4.0.5 on 2023-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='Document',
            field=models.IntegerField(db_index=True, default=1005831754, verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='number_phone',
            field=models.IntegerField(default=1, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Document',
            field=models.IntegerField(default=1, unique=True, verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='number_phone',
            field=models.IntegerField(default=1, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Token'),
        ),
    ]
